validation data
TeamTiramisy/CheckRunner pull request #2
Opened 2022-03-11 19:45 UTC by TeamTiramisy

2022-03-12 07:46 UTC, ZIban89 requested changes

2022-03-12 07:46 UTC, ZIban89 commented on src/com/console/check/CheckRunner.java
> +        String file = "C:\\Users\\User\\IdeaProjects\\CheckRunner\\fileCheck\\products.txt";
Заменить на путь относительно проекта! "fileCheck/products.txt"

2022-03-12 07:46 UTC, ZIban89 commented on src/com/console/check/CheckRunner.java
> +        File file = Path.of("C:\\Users\\User\\IdeaProjects\\CheckRunner\\fileCheck\\check.txt").toFile();
На относительный

2022-03-12 07:46 UTC, ZIban89 commented on src/com/console/check/regex/RegexData.java
> +        Path path = Path.of("C:\\Users\\User\\IdeaProjects\\CheckRunner\\fileCheck\\invalidData.txt");
и тут на относительный

2022-03-12 07:46 UTC, ZIban89 commented on src/com/console/check/regex/RegexData.java
> +        String regex = "(?<!.)([1-9]\\d?|100);([А-Я][а-я]{2,29});([1-9]\\d?\\.\\d\\d|100\\.00);([1-9]|[1]\\d|20)(?!.)";
Ещё б латиницу поддерживало

2022-03-12 08:32 UTC, ZIban89 approved these changes

2022-03-13 18:25 UTC, pavilion1900 approved these changes

2022-03-13 18:57 UTC, closed without merging